// File generated by `flutterfire configure`.
// Generated on: 2026-02-26

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// The options the `FlutterFire` CLI generates for each supported platform.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // Replace these with your Firebase configuration values
    // You can get these from Firebase Console project settings
    throw UnsupportedError(
      'DefaultFirebaseOptions have not been configured for this platform.\n'
      'To configure, run the following commands:\n'
      '  firebase_cli configure\n'
      'Or follow these steps:\n'
      '1. Go to Firebase Console (console.firebase.google.com)\n'
      '2. Create a new project or select existing one\n'
      '3. Add Android, iOS, Web platforms\n'
      '4. Download google-services.json (Android) and GoogleService-Info.plist (iOS)\n'
      '5. Copy configurations below\n',
    );
  }

  // Example Android configuration (replace with your values):
  // static const FirebaseOptions android = FirebaseOptions(
  //   apiKey: 'YOUR_ANDROID_API_KEY',
  //   appId: 'YOUR_ANDROID_APP_ID',
  //   messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
  //   projectId: 'YOUR_PROJECT_ID',
  //   storageBucket: 'YOUR_STORAGE_BUCKET',
  // );

  // Example iOS configuration (replace with your values):
  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'YOUR_IOS_API_KEY',
  //   appId: 'YOUR_IOS_APP_ID',
  //   messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
  //   projectId: 'YOUR_PROJECT_ID',
  //   storageBucket: 'YOUR_STORAGE_BUCKET',
  //   iosClientId: 'YOUR_IOS_CLIENT_ID',
  // );

  // Example Web configuration (replace with your values):
  // static const FirebaseOptions web = FirebaseOptions(
  //   apiKey: 'YOUR_WEB_API_KEY',
  //   appId: 'YOUR_WEB_APP_ID',
  //   messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
  //   projectId: 'YOUR_PROJECT_ID',
  //   storageBucket: 'YOUR_STORAGE_BUCKET',
  //   authDomain: 'YOUR_PROJECT_ID.firebaseapp.com',
  // );
}
